language: go

go: 1.13.x

matrix:
  include:
    - go: 1.13.x
      env: COVERAGE=true
    - go: 1.12.x
      env: COVERAGE=false
    - go: 1.11.x
      env: COVERAGE=false
    - go: 1.10.x
      env: COVERAGE=false
    - go: 1.9.x
      env: COVERAGE=false

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ./travis.sh

env:
  global:
    secure: "AHr7rzXYWGTIe8CvDLtEIwj3Arig7u9tQt1mWbB6E4VpTHOu1AeHMn/NXPm5aJV+eNfmRuiYQ4E2jswhHxcxp8M7fdqmNjOv8hGOuc1cyT2yKzD087qXHbreO5tfp/BMilFxzUe/tJRsSyj5RHNQ5krIQpnZMoqAX0IgtoPL5VI8w+xOM8PatUIGK9rVoYj3HXgUNrTGWPe6pCAKtKG3zZFnQlRZxfx+WAzMTu/oWnX9/HJEKHL9c5O8xHQvU2qlHVKoHpVVtZ1wchTrUJMjZotN1veZY40hJ+pStBrNmZCWRvaigAVaTIT8KERZGv83I4DIHQruDF/de5ecBEATSQ14KMvXLR4PGDPWeA8itlcspc0d2RiBTS8ClGhowlo5vxQ4rIim0Qy/+zMOeohGMgz8jqLer1Pt9hB5XKnZcigP1mAakDBNL45lXZxGC/w3SAI5+DHkkJmMaDbExhybkWCDgcWx+pNwoxN6/scWf2MMnZ361fRGPAc8namUxyhgwlp1DbJPcMduEq8XD8IUFMUCkRnz/8BAJx30aLWlj5eQ2GbjlNli3H3wV6RcXNzfuHBLIltITJjvrENsgeWOJ9skrVUx6EFzyBtHeKQEWaRiS4NJwttuvg7uAAB7Tf0NJVVeV3g7EJuoN1K244sGa4XQ4YxCXnQMLLcWVWL5SJc="
